# Generated by Django 3.2.2 on 2021-05-20 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(),
        ),
    ]
